train:
  batch_size: 64
  gradient_accumulation_steps: 1
  compile: true
  checkpoint: "./runs/lj70b56v/tinyasr-060000.pt" # small-bpe-text-pretrain.yaml

model:
  n_layers: 12
  d_model: 768
  n_heads: 12
  dropout: 0.1
  tokenizer: tinyasr.model