train:
  batch_size: 128
  gradient_accumulation_steps: 4
  compile: true

  val_every: 5000

model:
  n_layers: 12
  d_model: 768
  n_heads: 12
  dropout: 0.1
  tokenizer: tinyasr.model
  text_pretrain: true